# Generated by Django 5.0.3 on 2024-03-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date1', models.DateField()),
                ('note', models.TextField()),
            ],
        ),
    ]
