# Generated by Django 5.0.3 on 2024-03-21 12:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_appointment_delete_appointmentform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date1',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
