# Generated by Django 5.0.3 on 2024-03-22 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_appointment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='date1',
        ),
    ]
