# Generated by Django 5.0.3 on 2024-03-22 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='note',
        ),
    ]
