# Generated by Django 5.0.3 on 2024-03-22 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_message_contact_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='note',
            new_name='message',
        ),
    ]
