# Generated by Django 5.0.3 on 2024-03-23 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_appointment_reason_alter_newsletter_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='reason',
        ),
    ]
