# Generated by Django 5.0.3 on 2024-03-24 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_appointment_reason'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
